import '../styles/text.css'

export default function Text() {
    return (
        <div className="text">
            <h3>Lorem ipsum dolor sit amet</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas at massa et nisl efficitur commodo. Proin a dui in arcu rutrum gravida at vitae libero. Aenean convallis ante sed neque luctus, eu tincidunt tellus consectetur. Vivamus sed tristique dui. Curabitur venenatis augue quam, condimentum imperdiet justo sodales non. Integer egestas at lorem in euismod. Morbi tincidunt ex et turpis aliquet egestas. Quisque dictum convallis diam. Nullam dapibus auctor tempor. Etiam mollis eget velit vitae dapibus. Etiam massa erat, egestas at elit vel, elementum lobortis lectus. Vestibulum a augue dui. Curabitur diam tellus, accumsan at ipsum ac, suscipit convallis justo. Aenean orci nunc, ornare id lectus pulvinar, fringilla hendrerit lectus. Sed id massa eu arcu finibus ullamcorper. Fusce gravida aliquet erat eget tincidunt.</p>
            <p>Morbi maximus ipsum ac pretium sodales. In hac habitasse platea dictumst. Nunc finibus tempor pretium. Suspendisse dolor metus, varius cursus sem a, tempor rhoncus ante. Aliquam tempus laoreet libero nec aliquam. Fusce volutpat sed tellus eget malesuada. Cras id iaculis dolor, eget condimentum leo. Fusce scelerisque sem eu facilisis tincidunt. Nullam commodo faucibus dui ut sollicitudin. Duis in turpis convallis, aliquet nibh id, sollicitudin enim.</p>
            <p>Cras rutrum est quis porta dapibus. Praesent magna orci, efficitur non viverra id, malesuada eu erat. Vestibulum consectetur lobortis ligula, non tempus justo porttitor et. Aenean scelerisque turpis sed accumsan mollis. Donec auctor suscipit est, sit amet mattis quam porttitor ac. Duis leo dui, maximus sed consectetur eget, porta eu neque. Suspendisse tincidunt nec nibh ac mollis. Cras sed lectus risus. Duis magna odio, semper sit amet vestibulum ac, sodales nec nisl. Vivamus placerat tortor iaculis lectus mollis tincidunt. Suspendisse eu justo vehicula, egestas ligula ac, varius orci. Curabitur euismod urna eget neque interdum, at malesuada mauris congue. Integer in diam nec arcu consectetur egestas. In hac habitasse platea dictumst.</p>
        </div>
    )
}